POST http://localhost:4560/order/add
Content-Type: application/json

 {

        "CUSTOMER_ID":6,
        "ORDER_AMOUNT": 405,
        "ORDER_CURRENT_STATUS" : "New"

}

###
DELETE http://localhost:4560/order/DELETE/1


###
PUT  http://localhost:4560/order/update/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvdWZpcSIsImVtYWlsIjoidG91ZmlxQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjY2MzIwNjAzLCJleHAiOjE2NzQwOTY2MDN9.v1_mDvD8vH6GW4I60XpwkIt9T5roUHsmLZoFhGOtfno
Content-Type: application/json

{
    "ORDER_AMOUNT": 64651
}

###
GET http://localhost:4560/order/get-order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvdWZpcSIsImVtYWlsIjoidG91ZmlxQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjY2MzIwNjAzLCJleHAiOjE2NzQwOTY2MDN9.v1_mDvD8vH6GW4I60XpwkIt9T5roUHsmLZoFhGOtfno
Content-Type: application/json

{
    "itemsPerPage": 1,
    "currentPageNumber": 0,
    "sort": "asc",
    "orderBy": ""
}

###
GET http://localhost:4560/order/order-id-info/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvdWZpcSIsImVtYWlsIjoidG91ZmlxQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjY2MzIwNjAzLCJleHAiOjE2NzQwOTY2MDN9.v1_mDvD8vH6GW4I60XpwkIt9T5roUHsmLZoFhGOtfno
Content-Type: application/json

{
    "itemsPerPage": 1,
    "currentPageNumber":0,
    "sort": "asc",
    "orderBy": ""
}


