###
DELETE http://localhost:4560/evidence-pdf/delete-pdf/203

###
POST http://localhost:4560/evidence-pdf/re-generate-pdf/206
Content-Type: application/json

{
    "pdfData": 
     [
        {
            "uxsh_detail_table_id":"1",
            "company_address": "東京都千代⽥区岩本町3-9-17 スリーセブンビル8F 本町3-9-17 スリーセブンビル8F",
            "processing_number": "1000",
            "erase_software": "FlashErase LEGACY",
            "erase_method": "Full(0x0000)",
            "vendor_name": "narshingdi",
            "manufacturer": "PC-LL570LG",
            "product_serial": "7Z10849CA",
            "disk_model_no": "Unknown ATA Device",
            "disk_space": "160.0GB",
            "serial_no": "Unknown",
            "comment": "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of 'de Finibus Bonorum et Malorum' (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, 'Lorem ipsum dolor sit amet..', comes from a line in section 1.10.32."
        }
    ]
}



###
POST http://localhost:4560/evidence-pdf/generate-pdf
Content-Type: application/json

{
    "pdfData": 
  [
    {
        "uxsh_detail_table_id": "1",
        "company_address": "東京都千代⽥区岩本町3-9-17 スリーセブンビル8F 本町3-9-17 スリーセブンビル8F",
        "processing_number": "1",
        "erase_software": "FlashErase LEGACY",
        "erase_method": "Full(0x0000)",
        "vendor_name": "NEC",
        "manufacturer": "PC-LL570LG",
        "product_serial": "7Z10849CA",
        "disk_model_no": "Unknown ATA Device",
        "disk_space": "160.0GB",
        "serial_no": "Unknown",
        "comment": ""
    },
    {
        "uxsh_detail_table_id": "2",
        "company_address": "東京都千代⽥区岩本町3-9-17 スリーセブンビル8F 本町3-9-17 スリーセブンビル8F",
        "processing_number": "2",
        "erase_software": "FlashErase LEGACY",
        "erase_method": "Full(0x0000)",
        "vendor_name": "NEC",
        "manufacturer": "PC-LL570LG",
        "product_serial": "7Z10849CA",
        "disk_model_no": "Unknown ATA Device",
        "disk_space": "160.0GB",
        "serial_no": "Unknown",
        "comment": ""
    },
    {
        "uxsh_detail_table_id": "3",
        "company_address": "東京都千代⽥区岩本町3-9-17 スリーセブンビル8F 本町3-9-17 スリーセブンビル8F",
        "processing_number": "3",
        "erase_software": "FlashErase LEGACY",
        "erase_method": "Full(0x0000)",
        "vendor_name": "NEC",
        "manufacturer": "PC-LL570LG",
        "product_serial": "7Z10849CA",
        "disk_model_no": "Unknown ATA Device",
        "disk_space": "160.0GB",
        "serial_no": "Unknown",
        "comment": ""
    },
    {
        "uxsh_detail_table_id": "4",
        "company_address": "東京都千代⽥区岩本町3-9-17 スリーセブンビル8F 本町3-9-17 スリーセブンビル8F",
        "processing_number": "4",
        "erase_software": "FlashErase LEGACY",
        "erase_method": "Full(0x0000)",
        "vendor_name": "NEC",
        "manufacturer": "PC-LL570LG",
        "product_serial": "7Z10849CA",
        "disk_model_no": "Unknown ATA Device",
        "disk_space": "160.0GB",
        "serial_no": "Unknown",
        "comment": ""
    },
    {
        "uxsh_detail_table_id": "5",
        "company_address": "東京都千代⽥区岩本町3-9-17 スリーセブンビル8F 本町3-9-17 スリーセブンビル8F",
        "processing_number": "5",
        "erase_software": "FlashErase LEGACY",
        "erase_method": "Full(0x0000)",
        "vendor_name": "NEC",
        "manufacturer": "PC-LL570LG",
        "product_serial": "7Z10849CA",
        "disk_model_no": "Unknown ATA Device",
        "disk_space": "160.0GB",
        "serial_no": "Unknown",
        "comment": ""
    },
    {
        "uxsh_detail_table_id": "6",
        "company_address": "東京都千代⽥区岩本町3-9-17 スリーセブンビル8F 本町3-9-17 スリーセブンビル8F",
        "processing_number": "6",
        "erase_software": "FlashErase LEGACY",
        "erase_method": "Full(0x0000)",
        "vendor_name": "NEC",
        "manufacturer": "PC-LL570LG",
        "product_serial": "7Z10849CA",
        "disk_model_no": "Unknown ATA Device",
        "disk_space": "160.0GB",
        "serial_no": "Unknown",
        "comment": ""
    },
    {
        "uxsh_detail_table_id": "7",
        "company_address": "東京都千代⽥区岩本町3-9-17 スリーセブンビル8F 本町3-9-17 スリーセブンビル8F",
        "processing_number": "7",
        "erase_software": "FlashErase LEGACY",
        "erase_method": "Full(0x0000)",
        "vendor_name": "NEC",
        "manufacturer": "PC-LL570LG",
        "product_serial": "7Z10849CA",
        "disk_model_no": "Unknown ATA Device",
        "disk_space": "160.0GB",
        "serial_no": "Unknown",
        "comment": ""
    },
    {
        "uxsh_detail_table_id": "8",
        "company_address": "東京都千代⽥区岩本町3-9-17 スリーセブンビル8F 本町3-9-17 スリーセブンビル8F",
        "processing_number": "8",
        "erase_software": "FlashErase LEGACY",
        "erase_method": "Full(0x0000)",
        "vendor_name": "NEC",
        "manufacturer": "PC-LL570LG",
        "product_serial": "7Z10849CA",
        "disk_model_no": "Unknown ATA Device",
        "disk_space": "160.0GB",
        "serial_no": "Unknown",
        "comment": ""
    },
    {
        "uxsh_detail_table_id": "9",
        "company_address": "東京都千代⽥区岩本町3-9-17 スリーセブンビル8F 本町3-9-17 スリーセブンビル8F",
        "processing_number": "9",
        "erase_software": "FlashErase LEGACY",
        "erase_method": "Full(0x0000)",
        "vendor_name": "NEC",
        "manufacturer": "PC-LL570LG",
        "product_serial": "7Z10849CA",
        "disk_model_no": "Unknown ATA Device",
        "disk_space": "160.0GB",
        "serial_no": "Unknown",
        "comment": ""
    },
    {
        "uxsh_detail_table_id": "10",
        "company_address": "東京都千代⽥区岩本町3-9-17 スリーセブンビル8F 本町3-9-17 スリーセブンビル8F",
        "processing_number": "10",
        "erase_software": "FlashErase LEGACY",
        "erase_method": "Full(0x0000)",
        "vendor_name": "NEC",
        "manufacturer": "PC-LL570LG",
        "product_serial": "7Z10849CA",
        "disk_model_no": "Unknown ATA Device",
        "disk_space": "160.0GB",
        "serial_no": "Unknown",
        "comment": ""
    }
]
    
}
