
###
POST http://localhost:3000/evidence-pdf/generate-pdf
Content-Type: application/json

{
    "pdfData":[
        {
            "company_address": "東京都千代⽥区岩本町3-9-17 スリーセブンビル8F 本町3-9-17 スリーセブンビル8F",
            "processing_number": "1",
            "erase_software": "FlashErase LEGACY",
            "erase_method": "Full(0x0000)",
            "vendor_name": "NEC",
            "manufacturer": "PC-LL570LG",
            "product_serial": "7Z10849CA",
            "disk_model_no": "Unknown ATA Device",
            "disk_space": "160.0GB",
            "serial_no": "Unknown",
            "comment": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."

        }]
}