POST http://localhost:4560/product/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpZmF5ZXQxIiwiZW1haWwiOiJyaWZheWV0MUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY2NjMxODI1OCwiZXhwIjoxNjc0MDk0MjU4fQ.Ju6COI3l-3REBKW6J3_y7RIpoCWp1N-5Ki3u72NT-tY
Content-Type: application/json

 {
        "SUPPLIER_ID":1,
        "PRODUCT_NAME": "Chanachur",
        "PRODUCT_UNIT_PRICE": 53.5,
        "PRODUCT_PACKAGE": "DHAMAKA",
        "PRODUCT_IMAGE" : "jshgsjdk"
}

###
DELETE http://localhost:4560/product/delete/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpZmF5ZXQxIiwiZW1haWwiOiJyaWZheWV0MUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY2NjMxODI1OCwiZXhwIjoxNjc0MDk0MjU4fQ.Ju6COI3l-3REBKW6J3_y7RIpoCWp1N-5Ki3u72NT-tY
###
PUT http://localhost:4560/product/update/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpZmF5ZXQiLCJlbWFpbCI6InJpZmF5ZXRAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NjYzMjAzMzAsImV4cCI6MTY3NDA5NjMzMH0.N7tKAsphcqZFQpBWpRMBSgLv_NeYiO_hkrC5yG8UBZI
Content-Type: application/json

{

"PRODUCT_PACKAGE": "Normal"
}


### 
GET http://localhost:4560/product/product-all-information
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpZmF5ZXQxIiwiZW1haWwiOiJyaWZheWV0MUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY2NjMxODI1OCwiZXhwIjoxNjc0MDk0MjU4fQ.Ju6COI3l-3REBKW6J3_y7RIpoCWp1N-5Ki3u72NT-tY


###
GET http://localhost:4560/product/product-Id-Quantity-information/27
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpZmF5ZXQxIiwiZW1haWwiOiJyaWZheWV0MUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY2NjMxODI1OCwiZXhwIjoxNjc0MDk0MjU4fQ.Ju6COI3l-3REBKW6J3_y7RIpoCWp1N-5Ki3u72NT-tY
Content-Type: application/json

{
    "itemsPerPage": 2,
    "currentPageNumber":0 ,
    "sort": "asc",
    "orderBy": ""
}

###
GET http://localhost:4560/product/get-product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvdWZpcSIsImVtYWlsIjoidG91ZmlxQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjY2MzIwNjAzLCJleHAiOjE2NzQwOTY2MDN9.v1_mDvD8vH6GW4I60XpwkIt9T5roUHsmLZoFhGOtfno
Content-Type: application/json

{
    "itemsPerPage": 2,
    "currentPageNumber":0 ,
    "sort": "asc",
    "orderBy": ""
}
